# Generated by Django 4.2 on 2023-06-13 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_districts', to='search.district')),
            ],
        ),
        migrations.DeleteModel(
            name='GraphNode',
        ),
        migrations.AddField(
            model_name='distance',
            name='destination_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_distances', to='search.district'),
        ),
        migrations.AddField(
            model_name='distance',
            name='source_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_distances', to='search.district'),
        ),
    ]
