# Generated by Django 4.2 on 2023-06-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_district_parent_districts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='parent_districts',
            field=models.ManyToManyField(blank=True, related_name='child_districts', to='search.district'),
        ),
    ]
